version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"

  hapi:
    build: .
    ports:
      - "3000:3000"
    depends_on:
        - db

  gql:
    build: ../game-of-life-realtime
    ports:
      - "4000:4000"

  gatsby:
    build: ../game-of-life-front
    ports:
      - "80:9000"
    command: sh -c "gatsby build && gatsby serve -H '0.0.0.0'"

  redis:
    image: redis
    ports:
      - "6379:6379"