version: '3'

services:

  game-of-life-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"

  hapi:
    build: .
    ports:
      - "3000:3000"
    depends_on:
        - game-of-life-db

  gql:
    build: ../game-of-life-realtime
    ports:
      - "4000:4000"

  redis:
    image: redis
    ports:
      - "6379:6379"